### ISSUE TITLE
[통계] 관리자는 특정 기간 내의 일별 매출을 그래프로 조회할 수 있습니다. 

### ISSUE THREAD

**Issue by seongyeongit** [ssg-java3-240304/shop-Kick-n-Go#3]
# 🌈 Success criteria
1. 판매분석-기간별 매출 분석-일별 매출 그래프 (SAL-001)

# 👷To-do
- [ ]  일별 매출 데이터는 막대그래프 또는 선그래프로 시각화됩니다. 
- [ ] 이때 사용되는 데이터는 주문 테이블의 주문ID, 주문일시, 주문상태, 총금액 컬럼을 참조합니다. 
- 주문ID는 주문을 식별하는 고유 번호로 사용되며, 주문일시는 주문이 완료된 시간을 나타냅니다. 
- 주문상태는 주문의 상태를 나타내며, '결제 완료', '배송 준비 중', '배송 중', '배송 완료' 상태인 주문만 집계에 포함됩니다. 
- 총금액은 각 주문의 총 금액을 나타냅니다.

# 👓 Review
1.

**Comment by ooANAoo** [comment]
통계 ui 초기 세팅 완료

**Comment by seongyeongit** [comment]
![image](https://github.com/ssg-java3-240304/shop-Kick-n-Go/assets/162237255/60893317-db68-485a-8b87-19230f0ef80b)

![image](https://github.com/ssg-java3-240304/shop-Kick-n-Go/assets/162237255/4ec47fca-5ece-47cb-97e7-e2e7965888fe)

-> 오늘로부터 3일전까지의 매출을 확인

![image](https://github.com/ssg-java3-240304/shop-Kick-n-Go/assets/162237255/30dd3f2f-bb77-4b00-9076-f15dc02fb21e)

-> 테이블 상 값 중 '결제 완료', '배송 준비 중', '배송 중', '배송 완료', 인 값은 420000원 뿐
